Set auto=CreateObject("wscript.shell")
do
 Dim oFile
 Dim shell
 Set oShell = CreateObject("WScript.Shell")
 user = oShell.ExpandEnvironmentStrings("%Temp%")
 Set oFile = CreateObject("Wscript.Shell")
 Set oFile = oFile.CreateTextFile("%Temp%\TRASH.txt")
 oFile.WriteLine "AAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaAAGJSAJDAJSHDJKHASHJKDAHJKJKHDSAJKHDASJHKADSJKHDASJKHDASKJHJKHADSJKHDASKHJDSAKHJKJHDASKHJDASJKHJKSJKHDSAHJKDASJKHDKAJSHKHADSDASHKIUDASDASHJDASKJHDASKJHKDJSAHJHKDASHKJDSAKJHDSAKDASKJDASKHADSHKKJHADSJDSAJHDASKJHASDHJKJHKADS"
 oFile.Close
loop
